version: '3.1'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3308:3306
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: testhaha
  mongo:
    image: mongo
    restart: always
    volumes:
      - "./datamongo:/data/db"
    ports:
      - 27017:27017
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8000:80
    environment:
      PMA_PASSWORD: 1234
      PMA_USER: root
      PMA_HOSTS: mysql

  angular-service:
    # The name of the service
    container_name: plot-hole-design # Container name
    build: ./plot-hole-design # Location of our Dockerfile
    volumes:
      # Volume binding
      - './plot-hole-design:/usr/src/app'
    ports:
      - '4200:4200' # Port mapping
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
